spring:
  application:
    name: cheese
  datasource:
    url: jdbc:postgresql://localhost:5432/cheese
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        mode: always
server:
  port: 3000